// <auto-generated />
namespace KutuphaneYonetimSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBKutuphaneYonetimiAddAbstract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBKutuphaneYonetimiAddAbstract));
        
        string IMigrationMetadata.Id
        {
            get { return "202401121220155_[DBKutuphaneYonetimiAddAbstract]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
