// <auto-generated />
namespace KutuphaneYonetimSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbMigrationSon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbMigrationSon));
        
        string IMigrationMetadata.Id
        {
            get { return "202401121540085_[dbMigrationSon]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
